project:
  type: website
  output-dir: docs

website:
  title: "PHY117S24"
  navbar:
    background: primary #color of background is primary color in palette
    search: true
    #left is left-aligned top bar
    left:
      - href: index.qmd
        text: Home
      - href: https://phy117.github.io/
        text: "Course Description"
        target: _blank #makes it open in new page
      - href: https://docs.google.com/spreadsheets/d/1NN6zv30J_MdUYzjDmjOMn1q-IKhxN0H8w9O3rMQsQ1A/edit?usp=sharing
        text: "Schedule" 
        target: _blank #makes it open in new page
      - sidebar:syllabus
      - sidebar:coursecontent
            
  sidebar:
    - id: syllabus
      title: "Syllabus and FAQ"
      style: "docked"
      background: light
      contents:
       - starthere.qmd
       - syllabus.qmd
       - FAQ.qmd
       
    - id: coursecontent
      title: "Course Content"
      style: "docked"
      background: light
      contents:
       - coursecontent.qmd
   
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



