---
title: "FAQ"
format: 
  html:
    toc: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    self-contained: true
editor: visual
jupyter: python3
---


## When are your office hours? {#officehours}

::: panel-tabset
# Casey

If you email me on a weekday, you can expect a response from me within 24 hours. If you email me on a weekend, you can expect a response from me by class time on Monday (or the first day back if it’s a long weekend or holiday).

# Manbir
:::

## When is ____ due?{#duedates}

## Can I have an extension?{#extensionpolicy}

Some assignments will have hard deadlines. These assignments include the first Cornell Notes assignment, the math assessment, and all the Growth Mindset assignments. The reason for these hard deadlines is due to the nature of the assignments – for example, it is not helpful for you to take the math assessment and discover in the last week of class that you really should review trig. For all other assignments, if you need an extension, you may request one using [this form](https://forms.gle/qTLy66bkUNZ5ibTj7). We recognize that things come up and you may require some flexibility at some point in the semester. Please feel free to reach out to your instructor if you are struggling to meet a deadline. We want to support you and make sure you have the best possible chance for success in this class!

## Can I revise and resubmit something I did poorly on?{#revisionpolicy}

## When will you reply to my email?{#emails}

Timely communication is really important, but in order to be effective instructors, we also need to be able to take breaks from email. Here are the expectations you can have of us with respect to email response time:

::: panel-tabset
# Casey

If you email me on a weekday, you can expect a response from me within 24 hours. If you email me on a weekend, you can expect a response from me by class time on Monday (or the first day back if it’s a long weekend or holiday).

# Manbir
:::


## Do you grade on a curve?{#gradingcurve}

Grades are not curved; your grade depends only on your own performance, supporting your fellow students will help every one of you.

## What the heck are Cornell Notes?? {#cornellnotes}

## What should I do if I get behind on my work?{#catchingup}
